name: testing

on:
  push:
    branches:
      - 'feature/**'
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE'
      - 'images/**'

jobs:

  terratest:
    name: terratest
    uses: ./.github/workflows/terratest.yml
    with:
      ENVIRONMENT: testing
      TERRAFORM_VERSION: '1.4.6'
      TIMEOUT: 15m
      FUNCTION: TestAwsEc2
      AWS_DEFAULT_REGION: ap-southeast-1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
